server:
 port: 8762

spring:
 application:
  name: service-hello

erueka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'