spring:
 application:
  name: api-getway

server:
  port: 5555

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka

zuul:
  routes:
   api-a-url:
    path: /service-feign/**
    serviceId: service-feign
#    url: http://localhost:8765/
